export const USERS_ADMIN_REQUEST="USERS_ADMIN_REQUEST"
export const USERS_ADMIN_SUCCESS="USERS_ADMIN_SUCCESS"
export const USERS_ADMIN_FAIL="USERS_ADMIN_FAIL"

export const ORDER_REMOVE_REQUEST="USERS_ADMIN_REQUEST"
export const ORDER_REMOVE_SUCCESS="ORDER_REMOVE_SUCCESS"
export const ORDER_REMOVE_FAIL="ORDER_REMOVE_FAIL"

export const PRODUCT_ADS_REQUEST="USERS_ADMIN_REQUEST"
export const PRODUCT_ADS_SUCCESS="PRODUCT_ADS_SUCCESS"
export const PRODUCT_ADS_FAIL="PRODUCT_ADS_FAIL"

export const PRODUCT_ADS_CREATE_REQUEST="USERS_ADMIN_REQUEST"
export const PRODUCT_ADS_CREATE_SUCCESS="PRODUCT_ADS_CREATE_SUCCESS"
export const PRODUCT_ADS_CREATE_FAIL="PRODUCT_ADS_CREATE_FAIL"

export const PRODUCT_ADS_DELETE_REQUEST="USERS_ADMIN_REQUEST"
export const PRODUCT_ADS_DELETE_SUCCESS="PRODUCT_ADS_DELETE_SUCCESS"
export const PRODUCT_ADS_DELETE_FAIL="PRODUCT_ADS_DELETE_FAIL"
