export const USERS_ADMIN_REQUEST="USERS_ADMIN_REQUEST"
export const USERS_ADMIN_SUCCESS="USERS_ADMIN_SUCCESS"
export const USERS_ADMIN_FAIL="USERS_ADMIN_FAIL"

export const ORDER_REMOVE_REQUEST="USERS_ADMIN_REQUEST"
export const ORDER_REMOVE_SUCCESS="ORDER_REMOVE_SUCCESS"
export const ORDER_REMOVE_FAIL="ORDER_REMOVE_FAIL"
