
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL';

export const PRODUCT_SAVE_REQUEST='PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS='PRODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL='PRODUCT_SAVE_FAIL';

export const PRODUCT_DELETE_REQUEST='PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS='PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL='PRODUCT_DELETE_FAIL';


export const PRODUCT_SAVE_SELLER_REQUEST='PRODUCT_SAVE_SELLER_REQUEST';
export const PRODUCT_SAVE_SELLER_SUCCESS='PRODUCT_SAVE_SELLER_SUCCESS';
export const PRODUCT_SAVE_SELLER_FAIL='PRODUCT_SAVE_SELLER_FAIL';


export const PRODUCT_LIKE_REQUEST='PRODUCT_LIKE_REQUEST';
export const PRODUCT_LIKE_SUCCESS='PRODUCT_LIKE_SUCCESS';
export const PRODUCT_LIKE_FAIL='PRODUCT_LIKE_FAIL';

export const PRODUCT_IMAGE_REQUEST='PRODUCT_IMAGE_REQUEST';
export const PRODUCT_IMAGE_SUCCESS='PRODUCT_IMAGE_SUCCESS';
export const PRODUCT_IMAGE_FAIL='PRODUCT_IMAGE_FAIL';