
export const  USER_SIGNIN_REQUEST ='USER_SIGNIN_REQUEST';
export const  USER_SIGNIN_SUCCESS ='USER_SIGNIN_SUCCESS';
export const  USER_SIGNIN_FAIL ='USER_SIGNIN_FAIL';
export const  USER_SIGN_OUT ='USER_SIGN_OUT'; 

export const  USER_REGISTER_REQUEST ='USER_REGISTER_REQUEST';
export const  USER_REGISTER_SUCCESS ='USER_REGISTER_SUCCESS';
export const  USER_REGISTER_FAIL ='USER_REGISTER_FAIL';


export const  USER_DETAILS_REQUEST ='USER_DETAILS_REQUEST';
export const  USER_DETAILS_SUCCESS ='USER_DETAILS_SUCCESS';
export const  USER_DETAILS_FAIL ='USER_DETAILS_FAIL';


export const  USER_DETAILS_UPDATE_REQUEST ='USER_DETAILS_UPDATE_REQUEST';
export const  USER_DETAILS_UPDATE_SUCCESS ='USER_DETAILS_UPDATE_SUCCESS';
export const  USER_DETAILS_UPDATE_FAIL ='USER_DETAILS_UPDATE_FAIL';
export const  USER_DETAILS_UPDATE_RESET ='USER_DETAILS_UPDATE_RESET';

export const  USERS_LIST_REQUEST ='USERS_LIST_REQUEST';
export const  USERS_LIST_SUCCESS ='USERS_LIST_SUCCESS';
export const  USERS_LIST_FAIL ='USERS_LIST_FAIL';


export const  USERS_REMOVE_REQUEST ='USERS_REMOVE_REQUEST';
export const  USERS_REMOVE_SUCCESS ='USERS_REMOVE_SUCCESS';
export const  USERS_REMOVE_FAIL ='USERS_REMOVE_FAIL';

export const USER_IMAGE_REQUEST='USER_IMAGE_REQUEST';
export const USER_IMAGE_SUCCESS='USER_IMAGE_SUCCESS';
export const USER_IMAGE_FAIL='USER_IMAGE_FAIL';


